### PR TITLE
fixing conflict

### PR DESCRIPTION
**Pull request by eamoranto**

### CODE REVIEW

**Comment by jdnordy** [comment]
Still looks like there is a merge conflict evan

**Comment by eamoranto** [comment]
Ya there was a space, I believe Tony fixed it


Sent from Yahoo Mail for iPhone


On Wednesday, April 15, 2020, 8:24 PM, Joshua Nordstrom <notifications@github.com> wrote:




Still looks like there is a merge conflict evan

**Comment by jdnordy** [comment]
Still says there is a merge conflict. See if you can resolve it.

**Comment by eamoranto** [comment]
Will do. I’ll take a look right after stand ups and breakfast


Sent from Yahoo Mail for iPhone


On Thursday, April 16, 2020, 8:51 AM, Joshua Nordstrom <notifications@github.com> wrote:




Still says there is a merge conflict. See if you can resolve it.

**Pull request closed without merging**
